spring:
  profiles:
    active: info-crawler-demo
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  application:
    name: aiop-web

server:
  tomcat:
    uri-encoding: UTF-8
  
mybatis:
  type-aliases-package: com.asiainfo.biapp.infocrawlerdemo.pojo
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:com/asiainfo/biapp/infocrawlerdemo/dao/mapper/*.xml
  
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  
